# Generated by Django 5.1.5 on 2025-01-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_user_idea_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(default='my_surname', max_length=100),
            preserve_default=False,
        ),
    ]
